from __future__ import annotations

from app.schemas.report import AffectedProduct, EvidenceSummary, InventoryImpact
from app.schemas.workflow import TicketState


def affected_product_from_state(state: TicketState) -> AffectedProduct:
    """
    Ground-truth product identity (drug/ndc/lot/classification) taken
    directly from TicketState -- never left to the LLM to restate, so it
    cannot drift from what was actually normalized/matched.
    """
    event = state.event_normalized
    return AffectedProduct(
        drug_name=event.drug_name if event else "unknown",
        ndc=event.ndc if event else None,
        lot=event.lot if event else None,
        classification=state.classification.value if state.classification else None,
    )


def inventory_impact_from_state(state: TicketState) -> InventoryImpact:
    """
    Ground-truth inventory figures taken directly from
    TicketState.impact_summary / inventory_result -- these are never
    generated by the LLM, only narrated around.
    """
    impact = state.impact_summary
    inventory = state.inventory_result
    uncertainty = None
    if inventory and inventory.needs_identity_review:
        uncertainty = inventory.identity_review_reason

    return InventoryImpact(
        matched=inventory.matched if inventory else False,
        affected_departments=(
            [department.value for department in impact.affected_departments] if impact else []
        ),
        total_quantity=impact.total_quantity if impact else 0,
        priority=impact.priority.value if impact else None,
        uncertainty=uncertainty,
    )


def evidence_summary_from_state(
    state: TicketState,
    key_findings: list[str] | None = None,
) -> EvidenceSummary:
    """
    Ground-truth evidence coverage taken directly from
    TicketState.sufficiency_check. Only `key_findings` (a narrative summary
    of what the evidence says) may come from the LLM -- the coverage score
    and source lists themselves are never model-generated.
    """
    sufficiency = state.sufficiency_check
    return EvidenceSummary(
        coverage_score=sufficiency.coverage_score if sufficiency else 0.0,
        found_sources=(
            [source.value for source in sufficiency.found_sources] if sufficiency else []
        ),
        missing_sources=(
            [source.value for source in sufficiency.missing_sources] if sufficiency else []
        ),
        key_findings=key_findings or [],
    )
